### ISSUE TITLE
Weird output of draft model

### ISSUE THREAD

**Issue by KaiLv69** [uw-mad-dash/decoding-speculative-decoding#2]
Hi, I try to use the 290M model (https://huggingface.co/minghaoyan/Wide-Sheared-LLaMA-290M)  and find that the output of the model collapses. 

```
input_text = 'the fox is'
input_ids = tensor([[    1,   278,  1701, 29916,   338]])
output_ids = tensor([[1,   278,  1701, 29916,   338,   263, 29871, 29896, 29929, 29929,29929, 29929, 29929, 29929, 29929, 29929, 29929, 29929, 29929, 29929]])
output = '<s> the fox is a 1999999999999'
```

**Comment by KaiLv69** [comment]
The 543M model looks good to me.

**Comment by MinghaoYan** [comment]
Yes, as shown in our paper, the 290M single-layer model is not very performant. 796M usually provides the best speedup as per our evaluations in the paper.
